{
 "title": "Microservices Dashboard",
 "tags": [ "microservices" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Orders Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orders_created_total) by (status)",
     "legendFormat": "Orders Created"
    }
   ]
  },
  {
   "title": "Total Payments Initiated",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(payments_initiated_total)", "legendFormat": "Payments Initiated" }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total[1m])",
     "legendFormat": "{{service}} - {{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Kafka Produced Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_messages_produced_total[1m])",
     "legendFormat": "{{topic}} Produced"
    }
   ]
  },
  {
   "title": "Kafka Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(kafka_messages_consumed_total[1m])",
     "legendFormat": "{{topic}} Consumed"
    }
   ]
  }
 ]
}